name: "Eval-action"
description: "A minimal custom GitHub Action that evaluates code"
inputs:
  repoToken:
    description: "The GITHUB_TOKEN secret"
    required: false
  api_host:
    description: "API host"
    required: true
  x_api_key:
    description: "API key"
    required: false
  type:
    description: "Type"
    required: true
  test_name:
    description: "Test name"
    required: true
  scenario_preset_id:
    description: "Scenarios"
    required: true
  model_id:
    description: "Model"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"

