name: "Eval-action"
description: "A minimal custom GitHub Action that evaluates code"
inputs:
  repoToken:
    description: "The GITHUB_TOKEN secret"
    required: false
  vla_endpoint:
    description: "VLA Endpoint"
    required: true
  vla_credentials:
    description: "VLA Credentials"
    required: true
  test_name:
    description: "Test name"
    required: true
  project_id:
    description: "Project"
    required: true
  model_id:
    description: "Model"
    required: true
  model_name:
    description: "Model name"
    required: true
  scenario_id:
    description: "Scenarios"
    required: true
  user_id:
    description: "User ID"
    required: true
  batch_id:
    description: "Batch ID"
    required: true
  type:
    description: "MultiAgent"
    required: true

    
runs:
  using: "node16"
  main: "dist/index.js"

